lib/bank_web/router.ex
defmodule BankWeb.Router do
  use BankWeb, :router

  # Admin
  import BankWeb.Backoffice.UserBackofficeAuth

  use Kaffy.Routes,
    scope: "/admin",
    pipe_through: [:browser, :require_authenticated_user_backoffice]

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_user_backoffice
  end

  ## Admin Authentication routes

  scope "/", BankWeb.Backoffice do
    pipe_through [:browser, :redirect_if_user_backoffice_is_authenticated]

    get "/users_backoffice/log_in", UserBackofficeSessionController, :new
    post "/users_backoffice/log_in", UserBackofficeSessionController, :create
    get "/users_backoffice/reset_password", UserBackofficeResetPasswordController, :new
    post "/users_backoffice/reset_password", UserBackofficeResetPasswordController, :create
    get "/users_backoffice/reset_password/:token", UserBackofficeResetPasswordController, :edit
    put "/users_backoffice/reset_password/:token", UserBackofficeResetPasswordController, :update
  end

  scope "/", BankWeb.Backoffice do
    pipe_through [:browser, :require_authenticated_user_backoffice]

    get "/users_backoffice/settings", UserBackofficeSettingsController, :edit
    put "/users_backoffice/settings", UserBackofficeSettingsController, :update

    get "/users_backoffice/settings/confirm_email/:token",
        UserBackofficeSettingsController,
        :confirm_email
  end

  scope "/", BankWeb.Backoffice do
    pipe_through [:browser]

    delete "/users_backoffice/log_out", UserBackofficeSessionController, :delete
    get "/users_backoffice/confirm", UserBackofficeConfirmationController, :new
    post "/users_backoffice/confirm", UserBackofficeConfirmationController, :create
    get "/users_backoffice/confirm/:token", UserBackofficeConfirmationController, :confirm
  end

  # Admin /

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/api", BankWeb do
    pipe_through :api

    scope "/v1", V1, as: :v1 do
      resources "/user", UserController

      get "/statements", StatementController, :index
      get "/statements/:account_id", StatementController, :show

      post "/transference", TransferenceController, :create
    end
  end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through [:fetch_session, :protect_from_forgery]
      live_dashboard "/dashboard", metrics: BankWeb.Telemetry
    end
  end
end

lib/bank_web/views/layout_view.ex
defmodule BankWeb.LayoutView do
  use BankWeb, :view
end

lib/bank_web/templates/layout/_user_backoffice_menu.html.eex
<ul>
<%= if @current_user_backoffice do %>
  <li><%= @current_user_backoffice.email %></li>
  <li><%= link "Settings", to: Routes.user_backoffice_settings_path(@conn, :edit) %></li>
  <li><%= link "Log out", to: Routes.user_backoffice_session_path(@conn, :delete), method: :delete %></li>
<% else %>
  <li><%= link "Log in", to: Routes.user_backoffice_session_path(@conn, :new) %></li>
<% end %>
</ul>

lib/bank_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Banco do Tempo</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <script defer type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </head>
  <body>
    <header>
      <section class="container">
        <nav role="navigation">
          <ul>
            <li><a href="https://www.facebook.com/groups/837082279745501">Banco do Tempo</a></li>
          </ul>
          <%= render "_user_backoffice_menu.html", assigns %>
        </nav>
        <a href="https://www.facebook.com/groups/837082279745501" class="logo">
          <img src="<%= Routes.static_path(@conn, "/images/bdt.png") %>" alt="BDT Floripa Logo"/>
        </a>
      </section>
    </header>
    <main role="main" class="container">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <%= @inner_content %>
    </main>
  </body>
</html>